all:
	arm-xilinx-linux-gnueabi-g++ ./fast_hdmi.cpp -o ./fast_hdmi.o -I ~/lab3/opencv/opencv-2.4.9/install/include -I ~/lab3/opencv/opencv-2.4.9/install/include/opencv -L ~/lab3/opencv/opencv-2.4.9/install/lib -lopencv_core -lopencv_imgproc -lopencv_highgui -lopencv_ml -lopencv_video -lopencv_features2d -lopencv_calib3d -lopencv_objdetect -lopencv_legacy -lopencv_flann -lpthread
